### ISSUE TITLE
Argumentos del Jar

### ISSUE THREAD

**Issue by nicolascevallosb** [Pvidal-1/uees-sd-2022-proyecto_final#3]
Al momento de ejecutar en la consola de Linux, debe aceptar argumentos.

**Comment by Pvidal-1** [comment]
$java -jar target/ProyectoFinal ip puerto boolean

-Boolean es true para lider, false para replica

**Comment by Pvidal-1** [comment]
Ya no es necesario el boolean, el comando para ejecutar desde el directorio es:

$ java -jar target/ProyectoFinal ip puerto
